# Generated by Django 3.2.1 on 2021-05-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_class',
            fields=[
                ('mNameEN', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('mNameJP', models.CharField(max_length=50)),
                ('mDescription', models.TextField(max_length=750)),
                ('mThumbnail', models.ImageField(null=True, upload_to='anime-thumbnails/')),
                ('mEpisodeCount', models.IntegerField(default=0)),
                ('mOnGoing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category_class',
            fields=[
                ('mCategoryName', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('mDescription', models.CharField(max_length=750, null=True)),
                ('mPicture', models.ImageField(null=True, upload_to='category-image/')),
                ('mAnimeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAnime_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mAnimeName', models.CharField(max_length=50)),
                ('mUserEmail', models.EmailField(max_length=254)),
                ('mUsername', models.CharField(max_length=50)),
                ('mMoreInfo', models.TextField(max_length=750, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyList_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mAddedDate', models.DateTimeField()),
                ('mAnime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.anime_class')),
                ('mUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mEpisodeNumber', models.IntegerField()),
                ('mNameEN', models.CharField(max_length=100)),
                ('mNameJP', models.CharField(max_length=100, null=True)),
                ('mLengthSecs', models.IntegerField()),
                ('mViews', models.IntegerField()),
                ('mReleaseDate', models.DateTimeField()),
                ('mThumbnail', models.ImageField(null=True, upload_to='episode-thumbnails/')),
                ('mAnime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.anime_class')),
            ],
        ),
        migrations.AddField(
            model_name='anime_class',
            name='mCategories',
            field=models.ManyToManyField(to='Content.Category_class'),
        ),
    ]
