# Generated by Django 3.2.1 on 2021-05-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20210514_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mLink', models.CharField(max_length=255)),
                ('mLanguage', models.CharField(max_length=100)),
                ('mShortLanguage', models.CharField(max_length=10)),
                ('mEpisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.episode_class')),
            ],
        ),
    ]
