# Generated by Django 3.2.1 on 2021-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_subtitle_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode_class',
            name='mSelfHosted',
            field=models.BooleanField(default=False),
        ),
    ]
