# Generated by Django 3.2.1 on 2021-05-19 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0006_submitanime_class_msubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mBody', models.TextField(max_length=750)),
                ('mPostDate', models.DateTimeField(auto_now_add=True)),
                ('mEpisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.episode_class')),
                ('mRepliedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.comment_class')),
                ('mUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
