# Generated by Django 3.2.1 on 2021-05-19 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0008_comment_class_mreplieduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Comment_Class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mReportDate', models.DateTimeField(auto_now_add=True)),
                ('mComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.comment_class')),
                ('mUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
