# Generated by Django 3.2.1 on 2021-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_report_comment_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_class',
            name='mNameJP',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
