# Generated by Django 3.2.1 on 2021-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_alter_anime_class_mnamejp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_class',
            name='mThumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category_class',
            name='mPicture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode_class',
            name='mThumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
