# Generated by Django 3.2.1 on 2021-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_auto_20210523_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_class',
            name='mDescription',
            field=models.TextField(),
        ),
    ]
