# Generated by Django 3.2.1 on 2021-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_alter_anime_class_mdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_class',
            name='mDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_class',
            name='mBody',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submitanime_class',
            name='mMoreInfo',
            field=models.TextField(null=True),
        ),
    ]
