# Generated by Django 3.2.3 on 2021-06-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0013_auto_20210523_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_class',
            name='mDescription',
        ),
        migrations.RemoveField(
            model_name='category_class',
            name='mPicture',
        ),
    ]
