# Generated by Django 3.2.3 on 2021-06-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0014_auto_20210622_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode_class',
            name='mSelfHosted',
        ),
    ]
