# Generated by Django 3.2.3 on 2021-07-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0015_remove_episode_class_mselfhosted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle_class',
            name='mLanguage',
            field=models.CharField(max_length=255),
        ),
    ]
