# Generated by Django 3.2.3 on 2021-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0016_alter_subtitle_class_mlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle_class',
            name='mLanguage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subtitle_class',
            name='mLink',
            field=models.CharField(max_length=255),
        ),
    ]
