# Generated by Django 3.2.5 on 2021-08-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0017_auto_20210706_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtitle_class',
        ),
    ]
