# Generated by Django 3.2.5 on 2021-08-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0018_delete_subtitle_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode_class',
            name='mVCDN',
            field=models.BooleanField(default=False),
        ),
    ]
