# Generated by Django 3.2.5 on 2021-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_alter_category_class_mcategoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode_class',
            name='mVideoFileLink',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
