# Generated by Django 3.2.5 on 2021-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0022_alter_episode_class_mvideofilelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps_class',
            fields=[
                ('mID', models.BigAutoField(primary_key=True, serialize=False)),
                ('mAppVersion', models.TextField()),
                ('mPlatform', models.TextField()),
                ('mIsLatestVersion', models.BooleanField(default=True)),
            ],
        ),
    ]
