# Generated by Django 3.2.5 on 2021-10-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0023_apps_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps_class',
            name='mDownloadURL',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='apps_class',
            name='mAppVersion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apps_class',
            name='mPlatform',
            field=models.CharField(max_length=255),
        ),
    ]
